data:
  name: imagenet1k
  root: /home/yeseo_item/data_14T/UADL/data/imagenet/full
  num_classes: 1000
logging:
  run_name: E1k_tcig
  tags: [imagenet1k, E1, cell_tcig]
model:
  pretrained: true
  pretrained_head: true
  score:
    name: tcig
    kwargs:
      kernel_size: 7
      init_W: 2.0
      learnable_gamma: false
