logging:
  run_name: E1_vanilla_meanpool
  tags: [imagenet100, E1, baseline, meanpool]
model:
  vanilla_pool: mean
  score:
    name: none
  aggregator:
    name: topk_channel
    kwargs:
      K: 98
