logging:
  run_name: E3_local_var_w8_patch_topk
  tags: [imagenet100, E3, patch_topk]
model:
  score:
    name: local_var
    kwargs:
      window_size: 8
  aggregator:
    name: topk_patch
    kwargs:
      K: 98
      channel_aggregator: mean

