logging:
  run_name: E6_local_var_K147
  tags: [imagenet100, E6, K_ablation]
model:
  score:
    name: local_var
    kwargs:
      window_size: 8
  aggregator:
    name: topk_channel
    kwargs:
      K: 147

